services:
  app:
    build:
      dockerfile: app.Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - app_node_modules:/app/node_modules
    user: "node"

volumes:
  app_node_modules:
